on:
  schedule:
    - cron: "0 3 1 * *"
  workflow_dispatch:
    inputs:
      ignore_cache:
        description: 'Ignore cache for this run'
        required: false
        type: boolean


jobs:
  check_image_update:
    runs-on: ubuntu-latest
    outputs:
      update: ${{ steps.detect_update.outputs.update }}
      tags: ${{ steps.get_tags.outputs.tags }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - run: mkdir -p .cache

      - name: Get Datetime
        id: get-datetime
        if: ${{ github.event.inputs.ignore_cache != 'true' }}
        run: |
          echo "datetime=$(/bin/date -u '+%Y%m%d%H%M%S%N')" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/cache@v3
        if: ${{ github.event.inputs.ignore_cache != 'true' }}
        with:
          path: .cache
          key: ${{ runner.os }}-docker-latest-tag-${{ steps.get-datetime.outputs.datetime }}
          restore-keys: |
            ${{ runner.os }}-docker-latest-tag-

      - id: detect_update
        run: |
          output=$(python3 ./detect-image-update.py)
          echo "update=$output" >> $GITHUB_OUTPUT
        working-directory: scripts

      - id: get_tags
        if: ${{ steps.detect_update.outputs.update == 'true' }}
        run: |
          output=$(python3 ./get-image-tags.py ghcr.io/${{ github.repository }})
          echo "tags=$output" >> $GITHUB_OUTPUT
        working-directory: scripts

  update_image:
    runs-on: ubuntu-latest
    needs: check_image_update
    if: ${{ needs.check_image_update.outputs.update == 'true' }}
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ needs.check_image_update.outputs.tags }}
